2024-06-25 13:19:58,735 - ERROR - Unexpected error occurred: [Errno 2] No such file or directory: 'src/urls.txt'
2024-06-25 13:21:35,168 - ERROR - Unexpected error occurred: [Errno 2] No such file or directory: 'src/urls.txt'
2024-06-25 13:23:47,293 - ERROR - Unexpected error occurred: [Errno 2] No such file or directory: 'src/urls.txt'
2024-06-25 13:25:38,195 - ERROR - An unexpected error occurred: [Errno 2] No such file or directory: 'src/urls.txt'
2024-06-25 13:28:38,816 - ERROR - Error occurred while searching for gotr00t0day on https://bitcoinforum.com/profile//gotr00t0day: HTTPSConnectionPool(host='bitcoinforum.com', port=443): Max retries exceeded with url: /profile//gotr00t0day (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
2024-06-25 13:28:45,968 - ERROR - Error occurred while searching for gotr00t0day on https://doxbin.com/user//gotr00t0day: HTTPSConnectionPool(host='doxbin.com', port=443): Max retries exceeded with url: /user//gotr00t0day (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7de787e403e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-25 13:28:47,612 - ERROR - Error occurred while searching for gotr00t0day on https://doxbin.com/upload//gotr00t0day: HTTPSConnectionPool(host='doxbin.com', port=443): Max retries exceeded with url: /upload//gotr00t0day (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7de787327020>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-25 13:31:42,712 - ERROR - Error occurred while searching for gotr00t0day on https://bitcoinforum.com/profile//gotr00t0day: HTTPSConnectionPool(host='bitcoinforum.com', port=443): Max retries exceeded with url: /profile//gotr00t0day (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
2024-06-25 13:31:49,643 - ERROR - Error occurred while searching for gotr00t0day on https://doxbin.com/upload//gotr00t0day: HTTPSConnectionPool(host='doxbin.com', port=443): Max retries exceeded with url: /upload//gotr00t0day (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x701bd6ee7ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-25 13:31:50,816 - ERROR - Error occurred while searching for gotr00t0day on https://doxbin.com/user//gotr00t0day: HTTPSConnectionPool(host='doxbin.com', port=443): Max retries exceeded with url: /user//gotr00t0day (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x701bd63c2390>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-25 13:34:03,122 - ERROR - Error occurred while searching for AnonCatalyst on https://bitcoinforum.com/profile//AnonCatalyst: HTTPSConnectionPool(host='bitcoinforum.com', port=443): Max retries exceeded with url: /profile//AnonCatalyst (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
2024-06-25 13:34:21,627 - ERROR - Error occurred while searching for AnonCatalyst on https://doxbin.com/user//AnonCatalyst: HTTPSConnectionPool(host='doxbin.com', port=443): Max retries exceeded with url: /user//AnonCatalyst (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7b11ca5bd5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-25 13:34:22,635 - ERROR - Error occurred while searching for AnonCatalyst on https://doxbin.com/upload//AnonCatalyst: HTTPSConnectionPool(host='doxbin.com', port=443): Max retries exceeded with url: /upload//AnonCatalyst (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7b11c9bace30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-25 13:35:03,406 - ERROR - Error occurred while checking for query in URL, title, description, or HTML content for URL: https://www.pbase.com//AnonCatalyst: 'utf-8' codec can't decode byte 0xe9 in position 2196: invalid continuation byte
2024-06-25 13:37:04,180 - ERROR - Error occurred while searching for AnonCatalyst on https://www.blip.fm//AnonCatalyst: HTTPSConnectionPool(host='www.blip.fm', port=443): Max retries exceeded with url: //AnonCatalyst (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7b11e2aaa540>, 'Connection to www.blip.fm timed out. (connect timeout=None)'))
